set_property PACKAGE_PIN R2 [get_ports BI_RBO]
set_property IOSTANDARD LVCMOS33 [get_ports BI_RBO]

set_property PACKAGE_PIN W5 [get_ports CLK]
set_property PACKAGE_PIN V17 [get_ports D]
set_property IOSTANDARD LVCMOS33 [get_ports CLK]
set_property IOSTANDARD LVCMOS33 [get_ports D]

set_property PACKAGE_PIN V19 [get_ports Q[3]]
set_property PACKAGE_PIN U19 [get_ports Q[2]]
set_property PACKAGE_PIN E19 [get_ports Q[1]]
set_property PACKAGE_PIN U16 [get_ports Q[0]]

set_property IOSTANDARD LVCMOS33 [get_ports Q[3]]
set_property IOSTANDARD LVCMOS33 [get_ports Q[2]]
set_property IOSTANDARD LVCMOS33 [get_ports Q[1]]
set_property IOSTANDARD LVCMOS33 [get_ports Q[0]]

set_property PACKAGE_PIN W4 [get_ports AN[3]]
set_property PACKAGE_PIN V4 [get_ports AN[2]]
set_property PACKAGE_PIN U4 [get_ports AN[1]]
set_property PACKAGE_PIN U2 [get_ports AN[0]]

set_property IOSTANDARD LVCMOS33 [get_ports AN[3]]
set_property IOSTANDARD LVCMOS33 [get_ports AN[2]]
set_property IOSTANDARD LVCMOS33 [get_ports AN[1]]
set_property IOSTANDARD LVCMOS33 [get_ports AN[0]]

set_property PACKAGE_PIN W7 [get_ports display[7]]
set_property PACKAGE_PIN W6 [get_ports display[6]]
set_property PACKAGE_PIN U8 [get_ports display[5]]
set_property PACKAGE_PIN V8 [get_ports display[4]]
set_property PACKAGE_PIN U5 [get_ports display[3]]
set_property PACKAGE_PIN V5 [get_ports display[2]]
set_property PACKAGE_PIN U7 [get_ports display[1]]
set_property PACKAGE_PIN V7 [get_ports DP]

set_property IOSTANDARD LVCMOS33 [get_ports display[7]]
set_property IOSTANDARD LVCMOS33 [get_ports display[6]]
set_property IOSTANDARD LVCMOS33 [get_ports display[5]]
set_property IOSTANDARD LVCMOS33 [get_ports display[4]]
set_property IOSTANDARD LVCMOS33 [get_ports display[3]]
set_property IOSTANDARD LVCMOS33 [get_ports display[2]]
set_property IOSTANDARD LVCMOS33 [get_ports display[1]]
set_property IOSTANDARD LVCMOS33 [get_ports DP]
