set_property PACKAGE_PIN W5 [get_ports mclk]
set_property IOSTANDARD LVCMOS33 [get_ports mclk]

set_property PACKAGE_PIN V17 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports reset]

set_property PACKAGE_PIN T17 [get_ports btnClk]
set_property IOSTANDARD LVCMOS33 [get_ports btnClk]

set_property PACKAGE_PIN R2 [get_ports switch[1]]
set_property PACKAGE_PIN T1 [get_ports switch[0]]
set_property IOSTANDARD LVCMOS33 [get_ports switch[1]]
set_property IOSTANDARD LVCMOS33 [get_ports switch[0]]


set_property PACKAGE_PIN W4 [get_ports an[3]]
set_property PACKAGE_PIN V4 [get_ports an[2]]
set_property PACKAGE_PIN U4 [get_ports an[1]]
set_property PACKAGE_PIN U2 [get_ports an[0]]
set_property IOSTANDARD LVCMOS33 [get_ports an[3]]
set_property IOSTANDARD LVCMOS33 [get_ports an[2]]
set_property IOSTANDARD LVCMOS33 [get_ports an[1]]
set_property IOSTANDARD LVCMOS33 [get_ports an[0]]
set_property PACKAGE_PIN W7 [get_ports display[7]]
set_property PACKAGE_PIN W6 [get_ports display[6]]
set_property PACKAGE_PIN U8 [get_ports display[5]]
set_property PACKAGE_PIN V8 [get_ports display[4]]
set_property PACKAGE_PIN U5 [get_ports display[3]]
set_property PACKAGE_PIN V5 [get_ports display[2]]
set_property PACKAGE_PIN U7 [get_ports display[1]]
set_property PACKAGE_PIN V7 [get_ports display[0]]
set_property IOSTANDARD LVCMOS33 [get_ports display[7]]
set_property IOSTANDARD LVCMOS33 [get_ports display[6]]
set_property IOSTANDARD LVCMOS33 [get_ports display[5]]
set_property IOSTANDARD LVCMOS33 [get_ports display[4]]
set_property IOSTANDARD LVCMOS33 [get_ports display[3]]
set_property IOSTANDARD LVCMOS33 [get_ports display[2]]
set_property IOSTANDARD LVCMOS33 [get_ports display[1]]
set_property IOSTANDARD LVCMOS33 [get_ports display[0]]